# -*- coding: utf-8 -*-
"""app_test2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-LzB4t0hc5tkukVLst6CsLpfEdUZibrX
"""

# app.py - MedInsight AI Professional Version

import streamlit as st
import pandas as pd
import random
from openai import OpenAI
import altair as alt

# -----------------------------
# Page config
# -----------------------------
st.set_page_config(page_title="MedInsight AI", page_icon="🫀", layout="centered")

st.title("🫀 MedInsight AI")
st.subheader("Personalized Health Insights")
st.info(
    "This application provides educational, data-driven insights only. "
    "It does NOT provide medical advice or diagnosis."
)
st.divider()

# -----------------------------
# OpenAI API Key
# -----------------------------
st.sidebar.header("🔐 OpenAI API Key")
api_key = st.sidebar.text_input("Enter your OpenAI API Key", type="password")
if not api_key:
    st.warning("Please enter your OpenAI API key to continue.")
    st.stop()

client = OpenAI(api_key=api_key)

# -----------------------------
# Age-based recommended values
# -----------------------------
def get_recommended_values(age):
    return {
        "trestbps": 110 + (age - 20) * 0.5,      # BP slightly increases with age
        "chol": 180 + (age - 20) * 0.5,          # Cholesterol recommended
        "thalach": 220 - age,                     # Max HR formula
        "fbs": "No",                              # Fasting Blood Sugar
        "exang": "No",                            # Exercise Angina
        "oldpeak": 1.0                            # ST Depression
    }

# -----------------------------
# Generate random default values (persistent)
# -----------------------------
def random_sample(age):
    return {
        "age": age,
        "sex": random.choice(["Male", "Female"]),
        "cp": random.choice(["Typical Angina", "Atypical Angina", "Non-anginal Pain", "Asymptomatic"]),
        "trestbps": random.randint(100, 160),
        "chol": random.randint(150, 300),
        "fbs": random.choice(["No","Yes"]),
        "restecg": random.choice(["Normal", "ST-T wave abnormality", "Left ventricular hypertrophy"]),
        "thalach": random.randint(100, 200),
        "exang": random.choice(["No","Yes"]),
        "oldpeak": round(random.uniform(0.0, 5.0),1)
    }

if "default_values" not in st.session_state:
    random_age = random.randint(20, 70)
    st.session_state["default_values"] = random_sample(random_age)

# -----------------------------
# Personal Health Input
# -----------------------------
st.header("👤 Enter Your Health Data")
st.info("All fields are required. Default sample values are randomized and can be updated.")

# Age first
age = st.number_input("Age", min_value=20, max_value=120, value=st.session_state["default_values"]["age"], help="Your age in years (≥20).")
recommended_values = get_recommended_values(age)

sex = st.selectbox("Sex", ["Male", "Female"], index=0 if st.session_state["default_values"]["sex"]=="Male" else 1)
cp_options = ["Typical Angina", "Atypical Angina", "Non-anginal Pain", "Asymptomatic"]
cp = st.selectbox("Chest Pain Type", cp_options, index=cp_options.index(st.session_state["default_values"]["cp"]))

trestbps = st.number_input(f"Resting Blood Pressure (mm Hg) - Recommended: {recommended_values['trestbps']:.0f}",
                           min_value=50, max_value=250, value=st.session_state["default_values"]["trestbps"])
chol = st.number_input(f"Serum Cholesterol (mg/dl) - Recommended: {recommended_values['chol']:.0f}",
                       min_value=100, max_value=400, value=st.session_state["default_values"]["chol"])
fbs = st.selectbox("Fasting Blood Sugar >120 mg/dl?", ["No", "Yes"], index=0 if st.session_state["default_values"]["fbs"]=="No" else 1)
restecg_options = ["Normal", "ST-T wave abnormality", "Left ventricular hypertrophy"]
restecg = st.selectbox("Resting ECG Results", restecg_options, index=restecg_options.index(st.session_state["default_values"]["restecg"]))
thalach = st.number_input(f"Maximum Heart Rate Achieved - Recommended: {recommended_values['thalach']:.0f}",
                          min_value=50, max_value=250, value=st.session_state["default_values"]["thalach"])
exang = st.selectbox("Exercise-Induced Angina?", ["No", "Yes"], index=0 if st.session_state["default_values"]["exang"]=="No" else 1)
oldpeak = st.number_input(f"ST Depression (oldpeak) - Recommended: {recommended_values['oldpeak']}",
                          min_value=0.0, max_value=10.0, value=st.session_state["default_values"]["oldpeak"])

submit = st.button("Generate Insights")

if submit:
    # -----------------------------
    # User Data Table
    # -----------------------------
    st.subheader("📝 Your Entered Health Data vs Recommended")
    features = ["Age","Sex","Chest Pain Type","Resting BP","Cholesterol","Fasting Blood Sugar",
                "Resting ECG","Max Heart Rate","Exercise Angina","ST Depression"]
    values = [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak]
    recommended = ["-", "-", "-", f"{recommended_values['trestbps']:.0f}", f"{recommended_values['chol']:.0f}",
                   recommended_values["fbs"], "-", f"{recommended_values['thalach']:.0f}", recommended_values["exang"], recommended_values["oldpeak"]]

    df = pd.DataFrame({"Feature": features, "Value": values, "Recommended": recommended})

    # Color-coding table
    def color_row(val, rec):
        try:
            if rec in ["No", "Yes", "-"]:
                return ""
            val, rec = float(val), float(rec)
            return "background-color: lightgreen" if val <= rec else "background-color: salmon"
        except:
            return ""

    styled_df = df.style.apply(lambda x: [color_row(x["Value"], x["Recommended"]) for i in x], axis=1)
    st.dataframe(styled_df, use_container_width=True)

    # -----------------------------
    # Bar Chart Comparison
    # -----------------------------
    numeric_features = ["Resting BP", "Cholesterol", "Max Heart Rate", "ST Depression"]
    chart_df = pd.DataFrame({
        "Feature": numeric_features,
        "User Value": [trestbps, chol, thalach, oldpeak],
        "Recommended": [recommended_values['trestbps'], recommended_values['chol'], recommended_values['thalach'], recommended_values['oldpeak']]
    })
    chart_df = chart_df.melt(id_vars="Feature", var_name="Type", value_name="Value")
    st.subheader("📊 Visual Comparison with Recommended Values")
    chart = alt.Chart(chart_df).mark_bar().encode(
        x='Feature',
        y='Value',
        color='Type',
        tooltip=['Feature','Type','Value']
    ).properties(width=600)
    st.altair_chart(chart)

    # -----------------------------
    # AI Insights
    # -----------------------------
    st.subheader("💡 Personalized Educational Insights")
    with st.spinner("Generating AI insights..."):
        user_summary = f"""
User Health Profile:
- Age: {age}
- Sex: {sex}
- Chest Pain Type: {cp}
- Resting Blood Pressure: {trestbps}
- Cholesterol: {chol}
- Fasting Blood Sugar >120: {fbs}
- Resting ECG: {restecg}
- Max Heart Rate: {thalach}
- Exercise Angina: {exang}
- ST Depression: {oldpeak}
Recommended Values (Age-based):
- Resting BP: {recommended_values['trestbps']:.0f}
- Cholesterol: {recommended_values['chol']:.0f}
- Max Heart Rate: {recommended_values['thalach']:.0f}
- Fasting Blood Sugar: {recommended_values['fbs']}
- Exercise Angina: {recommended_values['exang']}
- ST Depression: {recommended_values['oldpeak']}
"""

        ai_prompt = f"""
You are a healthcare data analyst.
Generate educational insights for this user profile.
Explain which values are within or outside recommended ranges for the user's age.
Provide a brief report on whether it is advisable (educationally) for the user to consult a doctor.
Do NOT provide medical diagnosis.
{user_summary}
"""
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role":"system","content":"You are a healthcare data analyst."},
                {"role":"user","content":ai_prompt}
            ],
            max_tokens=600
        )

    insight_text = response.choices[0].message.content
    st.write(insight_text)

    # -----------------------------
    # Downloadable Report
    # -----------------------------
    st.download_button(
        label="Download Insights",
        data=insight_text,
        file_name="personal_health_insights.txt",
        mime="text/plain"
    )

